name: projet-is
channels:
  - pytorch # Pour PyTorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip # Ajouté pour suivre la recommandation de Conda
  # Core ML/Data Science
  - numpy>=2.0 # Contrainte pour compatibilité avec la résolution de dépendances pip perçue
  - pandas
  - scipy==1.15.3
  - scikit-learn
  - nltk
  - spacy>=3.7
  - pytorch # Ou torch, selon la dispo sur les canaux
  - transformers
  # Web & API
  - flask
  - requests
  # Utilities
  - pydantic>=2.0,<2.10
  - python-dotenv # s'importe comme dotenv
  - cryptography
  - tqdm
  - pyyaml # Pour parser environment.yml dans setup.py
  # Plotting & Graphing
  - matplotlib
  - seaborn
  - statsmodels
  - networkx==3.4.2
  # Java Bridge
  - jpype1
  # Logic & Reasoning
  - clingo
  # Testing - conda gère mieux pytest et coverage directement
  - pytest
  - pytest-cov # Alternative/complément à coverage, souvent préféré
  - pytest-mock
  - pytest-asyncio
  - coverage # Peut être redondant avec pytest-cov mais ne nuit pas
  - unidecode # Ajouté pour corriger ModuleNotFoundError
  - markdown # Ajouté pour corriger ModuleNotFoundError
  - pyvis # Ajouté pour la visualisation de réseaux (JTMS)
  - pip:
    - Flask-CORS # Spécifique, souvent via pip
    - flask_socketio>=5.3.6 # Pour le support des websockets dans le blueprint JTMS
    - semantic-kernel>=1.33.0 # Mise à jour CRITIQUE vers la nouvelle API
    - markdown
    - playwright
    - pytest-playwright
    - fastapi
    - "uvicorn[standard]"
    - a2wsgi>=1.8.0 # Ajout pour servir Flask avec Uvicorn
    # Note: semantic-kernel[agents] non disponible dans cette version
    # Fallback implémenté dans project_core/semantic_kernel_agents_fallback.py