name: projet-is
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python=3.10
  - pip

  # Core ML/Data Science
  - intel-openmp # Force une version unifiée d'OpenMP
  - mkl # Force l'utilisation des librairies Intel MKL
  - tbb # Threading Building Blocks, souvent lié à MKL
  - numpy=1.25.0 # Version figée pour la stabilité binaire
  - pandas=2.0.3
  - scipy
  - scikit-learn
  - nltk
  - spacy # Laisser conda choisir la version
  - pytorch
  - transformers
  - sympy=1.13.1
  - thinc=8.3.2 # Figé pour compatibilité avec spacy (8.3.4 non trouvé sur conda)

  # Web & API
  - flask
  - requests
  - fastapi
  - uvicorn
  - whitenoise
  - flask-cors
  - starlette
  - a2wsgi
  - asgiref

  # Utilities
  - pydantic
  - pydantic-settings
  - python-dotenv
  - cryptography
  - tqdm
  - pyyaml
  - regex
  - markdown
  - psutil
 
  # Plotting & Graphing
  - matplotlib
  - seaborn
  - statsmodels
  - networkx
  - pyvis
 
  # Logic & Reasoning
  - clingo

  # Testing
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-asyncio
  - coverage
  - unidecode
  - conda-lock

  # La section pip est pour les paquets non disponibles ou problématiques sur Conda
  - pip:
    - semantic-kernel>=1.33.0
    - flask_socketio>=5.3.6
    - playwright
    - pytest-playwright
    - psutil
    - ag2>=0.2.0
    - tenacity
    - pybreaker
    - pytest-dotenv
    - mcp
    - blis
    - JPype1>=1.5.0
