name: projet-is
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - clingo
  - jpype1
  - flask
  - matplotlib
  - networkx==3.4.2
  - pydantic>=2.0,<2.10
  - pandas
  - numpy<2.0 # Éviter NumPy 2.x pour compatibilité avec numpy.rec via pandas
  - scipy
  - scikit-learn
  - python-dotenv
  - pip
  - pip:
    - Flask-CORS
    - semantic-kernel==1.29.0
    - pytest-mock
    - pytest-asyncio
    - coverage