from setuptools import setup, find_packages

setup(
    name="argumentation_analysis_project",
    version="0.1.0",
    packages=find_packages(exclude=["tests", "tests.*", "scripts", "scripts.*", "docs", "docs.*", "notebooks", "notebooks.*", "venv", ".venv", "dist", "build", "*.egg-info", "_archives", "_archives.*", "examples", "examples.*", "config", "config.*", "services", "services.*", "tutorials", "tutorials.*", "libs", "libs.*", "results", "results.*", "src", "src.*"]),
    # package_dir={'': 'src'},
    install_requires=[
        "numpy>=2.0.0,<2.3",  # Ajusté pour thinc et scipy
        "pandas",
        "scipy==1.15.3",
        "scikit-learn",
        "nltk",
        # "spacy==3.8.7", # Temporairement retiré
        # "thinc==8.2.3",
        # "blis==0.7.11",
        # "srsly==2.5.1",
        # "preshed==3.0.10",
        # "murmurhash==1.0.13",
        # "cymem==2.0.11",
        "torch",
        "transformers",
        "pydantic>=2.0,<2.10",
        "requests",
        "matplotlib",
        "seaborn",
        "networkx==3.2.1",
        "python-dotenv",  # Pour l'import de 'dotenv'
        "semantic-kernel==1.29.0",
        "pytest",
        "pytest-cov",
        "pytest-mock",
        "pytest-asyncio",
        "coverage",
        "cryptography",
        "jpype1",
        "flask",
        "Flask-CORS",
        "tqdm",
        'markdown',
        "unidecode",
    ],
    python_requires=">=3.8",
    description="Système d'analyse argumentative",
    author="EPITA",
    author_email="contact@epita.fr",
)