graph LR
  arg_1(["arg_1"])
  arg_2(["arg_2"])
  arg_3(["arg_3"])
  arg_4(["arg_4"])
  arg_5(["arg_5"])
  arg_6(["arg_6"])
  arg_7(["arg_7"])
  arg_8(["arg_8"])
  arg_9(["arg_9"])
  arg_10(["arg_10"])
  fallacy_1{{"fallacy_1"}}
  fallacy_2{{"fallacy_2"}}
  fallacy_3{{"fallacy_3"}}
  fallacy_4{{"fallacy_4"}}
  fallacy_5{{"fallacy_5"}}
  fallacy_6{{"fallacy_6"}}
  fallacy_7{{"fallacy_7"}}
  fallacy_8{{"fallacy_8"}}
  fallacy_9{{"fallacy_9"}}
  fallacy_10{{"fallacy_10"}}
  fallacy_11{{"fallacy_11"}}
  fallacy_12{{"fallacy_12"}}
  fallacy_13{{"fallacy_13"}}
  fallacy_14{{"fallacy_14"}}
  jtms_1[/"fallacy_on_arg_5"/]
  jtms_2[/"fallacy_on_arg_2"/]
  jtms_3[/"fallacy_on_arg_2"/]
  jtms_4[/"fallacy_on_arg_3"/]
  jtms_5[/"fallacy_on_arg_2"/]
  jtms_6[/"fallacy_on_arg_2"/]
  brevision_1[\"brevision_1"\]
  ca_1>"<scrubbed>"]
  qual_arg_2[["qual_arg_2"]]
  qual_arg_3[["qual_arg_3"]]
  qual_arg_4[["qual_arg_4"]]
  qual_arg_5[["qual_arg_5"]]
  qual_arg_6[["qual_arg_6"]]
  arg_2 -->|counter_argument| ca_1
  arg_2 -->|quality_score| qual_arg_2
  arg_3 -->|quality_score| qual_arg_3
  arg_4 -->|quality_score| qual_arg_4
  arg_5 -->|quality_score| qual_arg_5
  arg_6 -->|quality_score| qual_arg_6