graph LR
  arg_1(["arg_1"])
  arg_2(["arg_2"])
  arg_3(["arg_3"])
  arg_4(["arg_4"])
  arg_5(["arg_5"])
  arg_6(["arg_6"])
  arg_7(["arg_7"])
  arg_8(["arg_8"])
  arg_9(["arg_9"])
  arg_10(["arg_10"])
  arg_11(["arg_11"])
  arg_12(["arg_12"])
  arg_13(["arg_13"])
  arg_14(["arg_14"])
  arg_15(["arg_15"])
  arg_16(["arg_16"])
  arg_17(["arg_17"])
  fallacy_1{{"fallacy_1"}}
  fallacy_2{{"fallacy_2"}}
  fallacy_3{{"fallacy_3"}}
  fallacy_4{{"fallacy_4"}}
  fallacy_5{{"fallacy_5"}}
  fallacy_6{{"fallacy_6"}}
  fallacy_7{{"fallacy_7"}}
  fallacy_8{{"fallacy_8"}}
  fallacy_9{{"fallacy_9"}}
  fallacy_10{{"fallacy_10"}}
  fallacy_11{{"fallacy_11"}}
  fallacy_12{{"fallacy_12"}}
  fallacy_13{{"fallacy_13"}}
  fallacy_14{{"fallacy_14"}}
  fallacy_15{{"fallacy_15"}}
  fallacy_16{{"fallacy_16"}}
  fallacy_17{{"fallacy_17"}}
  jtms_1[/"arg_1"/]
  jtms_2[/"arg_2"/]
  jtms_3[/"arg_3"/]
  jtms_4[/"arg_4"/]
  jtms_5[/"arg_5"/]
  jtms_6[/"arg_6"/]
  jtms_7[/"arg_7"/]
  jtms_8[/"arg_8"/]
  jtms_9[/"arg_9"/]
  jtms_10[/"arg_10"/]
  jtms_11[/"arg_11"/]
  jtms_12[/"fallacy_on_arg_1"/]
  jtms_13[/"fallacy_on_arg_1"/]
  brevision_1[\"brevision_1"\]
  ca_1>"<scrubbed>"]
  ca_2>"<scrubbed>"]
  ca_3>"<scrubbed>"]
  ca_4>"<scrubbed>"]
  ca_5>"<scrubbed>"]
  ca_6>"<scrubbed>"]
  ca_7>"<scrubbed>"]
  arg_1 -->|counter_argument| ca_1
  arg_2 -->|counter_argument| ca_2
  arg_3 -->|counter_argument| ca_3
  arg_4 -->|counter_argument| ca_4
  arg_5 -->|counter_argument| ca_5
  arg_1 -->|counter_argument| ca_6
  arg_2 -->|counter_argument| ca_7