graph LR
  arg_1(["arg_1"])
  arg_2(["arg_2"])
  arg_3(["arg_3"])
  arg_4(["arg_4"])
  arg_5(["arg_5"])
  arg_6(["arg_6"])
  arg_7(["arg_7"])
  arg_8(["arg_8"])
  arg_9(["arg_9"])
  fallacy_1{{"fallacy_1"}}
  ca_1>"<scrubbed>"]
  ca_2>"<scrubbed>"]
  ca_3>"<scrubbed>"]
  ca_4>"<scrubbed>"]
  ca_5>"<scrubbed>"]
  ca_6>"<scrubbed>"]
  qual_arg_1[["qual_arg_1"]]
  arg_1 -->|quality_score| qual_arg_1