graph LR
  arg_1(["premisses: Le peuple allemand "])
  arg_2(["premisses: La mobilisation et "])
  arg_3(["premisses: La démocratie et la"])
  arg_4(["premisses: L’Allemagne souffre"])
  arg_5(["premisses: L’« international J"])
  arg_6(["arguments"])
  arg_7(["premisses: Le peuple allemand "])
  arg_8(["premisses: Des provocations et"])
  arg_9(["premisses: La démocratie et la"])
  arg_10(["premisses: L'Allemagne est sur"])
  arg_11(["premisses: Les Juifs et l'‘int"])
  arg_12(["arguments"])
  arg_13(["premisses: Le peuple allemand "])
  arg_14(["premisses: L’ancien président "])
  arg_15(["premisses: La démocratie et la"])
  arg_16(["premisses: L’Allemagne souffre"])
  arg_17(["premisses: Les Juifs et l’«int"])
  fallacy_1{{"fallacy_1"}}
  fallacy_2{{"fallacy_2"}}
  fallacy_3{{"fallacy_3"}}
  fallacy_4{{"fallacy_4"}}
  fallacy_5{{"fallacy_5"}}
  fallacy_6{{"fallacy_6"}}
  fallacy_7{{"fallacy_7"}}
  fallacy_8{{"fallacy_8"}}
  fallacy_9{{"fallacy_9"}}
  fallacy_10{{"fallacy_10"}}
  fallacy_11{{"fallacy_11"}}
  fallacy_12{{"fallacy_12"}}
  fallacy_13{{"fallacy_13"}}
  fallacy_14{{"fallacy_14"}}
  fallacy_15{{"fallacy_15"}}
  fallacy_16{{"fallacy_16"}}
  fallacy_17{{"fallacy_17"}}
  jtms_1[/"arg_1"/]
  jtms_2[/"arg_2"/]
  jtms_3[/"arg_3"/]
  jtms_4[/"arg_4"/]
  jtms_5[/"arg_5"/]
  jtms_6[/"arg_6"/]
  jtms_7[/"arg_7"/]
  jtms_8[/"arg_8"/]
  jtms_9[/"arg_9"/]
  jtms_10[/"arg_10"/]
  jtms_11[/"arg_11"/]
  jtms_12[/"fallacy_on_arg_1"/]
  jtms_13[/"fallacy_on_arg_1"/]
  brevision_1[\"brevision_1"\]
  ca_1>"Le fait que des Allemands aien"]
  ca_2>"Attribuer la responsabilité de"]
  ca_3>"L'affirmation selon laquelle l"]
  ca_4>"Présenter seulement deux optio"]
  ca_5>"La prémisse universelle selon "]
  ca_6>"La souffrance passée du peuple"]
  ca_7>"Attribuer la responsabilité pr"]
  arg_1 -->|counter_argument| ca_1
  arg_2 -->|counter_argument| ca_2
  arg_3 -->|counter_argument| ca_3
  arg_4 -->|counter_argument| ca_4
  arg_5 -->|counter_argument| ca_5
  arg_1 -->|counter_argument| ca_6
  arg_2 -->|counter_argument| ca_7