graph LR
  arg_1(["arg_1"])
  arg_2(["arg_2"])
  arg_3(["arg_3"])
  arg_4(["arg_4"])
  arg_5(["arg_5"])
  qual_arg_2[["qual_arg_2"]]
  qual_arg_3[["qual_arg_3"]]
  qual_arg_4[["qual_arg_4"]]
  qual_arg_5[["qual_arg_5"]]
  arg_2 -->|quality_score| qual_arg_2
  arg_3 -->|quality_score| qual_arg_3
  arg_4 -->|quality_score| qual_arg_4
  arg_5 -->|quality_score| qual_arg_5